apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-logging
spec:
  storageClassName: elasticsearch-logging
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 7Gi

#---
#apiVersion: storage.k8s.io/v1
#kind: StorageClass
#metadata:
#  name: elasticsearch-logging
#provisioner: kubernetes.io/aws-ebs
#reclaimPolicy: Delete
#parameters:
#  type: gp2

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: elasticsearch-logging
parameters:
  fsType: ext4
  type: gp2
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
allowedTopologies:
- matchLabelExpressions:
  - key: failure-domain.beta.kubernetes.io/zone
    values:
    - us-west-2b
